spring.application.name=demo
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.datasource.username=postgres
spring.datasource.password=663804Qq!
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=VGhpc0lzQVN1cGVyTG9uZ1NlY3JldEtleUZvckpXVEFuZEl0TXVzdEJlQXRMZWFzdDMyQnl0ZXNMb25n
jwt.expiration=86400000000000