CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    login VARCHAR(255),
    password VARCHAR(255),
    email VARCHAR(255),
    created_at TIMESTAMP(6),
    role VARCHAR(255)
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(255),
    created_at TIMESTAMP(6),
    completed BOOLEAN NOT NULL,
    pinned BOOLEAN NOT NULL,
    reminder_at TIMESTAMP(6),
    reminder_sent BOOLEAN NOT NULL,
    status VARCHAR(255),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_tasks_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE telegram_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_chat_id BIGINT NOT NULL UNIQUE,
    telegram_user_id BIGINT NOT NULL,
    telegram_username VARCHAR(255),
    connected_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_telegram_connections_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE telegram_link_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    used BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_telegram_link_codes_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_tasks_user_id ON tasks (user_id);
CREATE INDEX idx_telegram_link_codes_user_id ON telegram_link_codes (user_id);
